language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - RUST_VERSION="$TRAVIS_RUST_VERSION" ./ci/test.sh
branches:
  except:
    - /.tmp$/
